[package]
name = "lol-async"
version = "0.1.1"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/lol-async"
repository = "https://github.com/jbr/lol-async"
description = "async html-rewriter"

[dependencies]
futures-lite = "1.11.3"
pin-project-lite = "0.2.6"
atomic-waker = "1.0.0"
ringbuf = "0.2.3"
lol_html = "0.3.0"

[dev-dependencies]
async-executor = "1.4.0"
async-io = "1.3.1"
async-global-executor = "2.0.2"
