[package]
name = "lol-async"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
futures-lite = "1.11.3"
parking_lot = "0.11.1"
pin-project-lite = "0.2.6"
async-channel = "1.6.1"
atomic-waker = "1.0.0"
ringbuf = "0.2.3"
lol_html = "0.3.0"

[dev-dependencies]
async-executor = "1.4.0"
async-io = "1.3.1"
async-global-executor = "2.0.2"
